- name: update apt cache
  apt: update_cache=yes cache_valid_time=3600
  become: yes
- name: install
  apt: name=nginx
  become: yes
- name: install python cryptography
  apt: name=python-cryptography
  become: yes
- name: install rsync
  apt: name=rsync
  become: yes
- name: Diffie-Hellman parameters
  openssl_dhparam: path={{ nginx_dhparam_path }} size={{ nginx_dhparam_size }}
  become: yes
- name: settings directory
  synchronize: src={{ nginx_directory }}/ dest=/etc/nginx owner=no group=no copy_links=yes
  become: yes
  notify: restart
- name: html directory (1/2)
  synchronize: src={{ nginx_html_directory }}/ dest=/usr/share/nginx/html owner=no group=no delete=yes
  become: yes
  notify: restart
- name: html directory (2/2)
  file: path=/usr/share/nginx/html state=directory owner=www-data group=www-data recurse=yes
  become: yes
  notify: restart
- name: disable sites (1/2)
  file: path=/etc/nginx/sites-enabled/ state=absent
  become: yes
- name: disable sites (2/2)
  file: path=/etc/nginx/sites-enabled/ state=directory
  become: yes
  notify: restart
- name: enable sites
  file: src=/etc/nginx/sites-available/{{ item }} dest=/etc/nginx/sites-enabled/{{ item }} state=link
  loop: "{{ nginx_sites }}" 
  become: yes
  notify: restart
- name: allow ports through ufw
  ufw: rule=allow port={{ item }} proto=tcp
  loop: "{{ nginx_ports }}" 
  become: yes
